name: Peribeco
encoding: UTF-8
domain: example.com 
disable_component_resolution_regex_fallback: 1
#default_view: VistaPrincipal

Model::LDAP::Correo:
    host: [FQDN LDAP SERVER]
    base: dc=example,dc=com
    dn: [USER LDAP]
    password: [PASSWORD LDAP] 
    start_tls: 0
    start_tls_options: 
        verify: none
    options: 
    connection_class: Peribeco::LDAP::Correo

Controller::HTML::FormFu:
    constructor:
        render_method: tt
        tt_args:
            encoding: UTF-8

View::HTML:
    encoding: UTF-8

HomePage:
    user: /personas/detalle
    admin: /personas/lista

Modulos:
    Personas:
        Active: 1
        Administrar: 1
        Modificar: 1
        Password: 1
        Detalle: 1
    Grupos: 1
    Listas: 1
    Quota: 1
    Reenvios: 1
    Vacations: 1

Menu: 
    Listas: 
        caption: Listas de Correo
        submenu: 
    Personas: 
        caption: Personas
        submenu: 
    Grupos: 
        caption: Grupos
        submenu: 
    Forwards: 
        caption: Reenvíos Automáticos
        submenu: 
    OutOffice: 
        caption: Fuera de Oficina
        submenu: 

# Listas Postfix
 
Correo::Listas:
    basedn: ou=listas,ou=people,dc=example,dc=com
    objectClass: qmailGroup groupOfNames
    filter: (objectClass=qmailGroup)
    attrs:
     nombre: cn
     descripcion: description
     miembro_correo: rfc822member
     miembro: member
     correo: mail
     moderador: dnmoderator
     mailhost: mailhost
    values:
     mailhost: [FQDN SMTP SERVER]
     sendmailMTAAliasGrouping: aliases

# Listas Sendmail
#Configuracion de listas con sendmailMTA
#Correo::Listas:
#    basedn: ou=Listas,dc=example,dc=com
#    objectClass: sendmailMTA sendmailMTAAlias sendmailMTAAliasObject CourierMailAccount
#    filter: (&(objectClass=sendmailMTA)(sendmailMTAAliasGrouping=aliases))
#    attrs:
#     nombre: sendmailMTAKey
#     descripcion: cn
#     miembro_correo: sendmailMTAAliasValue
#     miembro:
#     correo: mail
#     moderador: uid
#     mailhost: mailhost
#    values:
#     mailhost: [FQDN SMTP SERVER]
#     sendmailMTAAliasGrouping: aliases

# Configuración de reenvíos automáticos
#Correo::Reenvios:
#    basedn: ou=Aliases,ou=Correo,ou=Aplicaciones,o=Cantv,dc=example,dc=com 
#    objectClass: sendmailMTA sendmailMTAAlias sendmailMTAAliasObject CourierMailAccount
#    filter: (objectClass=sendmailMTA)
#    attrs:
#     nombre: sendmailMTAKey
#     miembro_correo: sendmailMTAAliasValue
#     correo: mail
#     mailhost: mailhost
#    values:
#     mailhost: [FQDN SMTP SERVER]
#     sendmailMTAAliasGrouping: aliases
#     domain: example2.com
#    entry:
#        default_attrs: 
#            sendmailMTAAliasGrouping: aliases
#            sendmailMTAAliasValue:
#            sendmailMTAKey:
#        dn_attr: sendmailMTAKey
#        objectclass_attr: sendmailMTA sendmailMTAAlias sendmailMTAAliasObject  

#Configuración Vacations
#Correo::Vacations:
#    basedn: ou=Personas,dc=example,dc=com
#    objectClass: Person
#    filter: (objectClass=Person)
#    attrs:
#     account: uid
#     active: vacationActive
#     mensaje: vacationInfo

#Configuración Quotas de correo
Correo::Quota:
    basedn: ou=people,dc=example,dc=com
    objectClass: Person
    filter: (objectClass=Person)
    attrs:
     account: uid 
     nombre: cn
     apellido: sn
     quota: mailQuotaSize 
     size: MB
    quota_info:    
     server: [FQDN QUOTA DOVEADM SOCKET] 
     port: [PORT QUOTA DOVEADM SOCKET]
     proto: tcp 

Personas:
    Detalle:
        attrs:
            dn: DN
            uid: Identificador
            givenName: Nombre
            sn: Apellido
            pager: Cedula
            mail: Correo
            mailhost: Mailhost
    Correo:
        attrs:
            mailhost: [FQDN SMTP SERVER]
    Values:
            mailhost: [FQDN SMTP SERVER]
            quota: [QUOTA SIZE]

#Atributos AD
AD::Forwards:
    attrs:
        maildomain: [FQDN SMTP SERVER AD]

Mail::Server:
    server: [FQDN MAIL SERVER]
    host: localhost
    port: [PORT SMTP SERVER]
    account: user@example.com
    pass: [PASSWORD]
    mail:
        subject: Confirmación de Migración
        message: Su cuenta ha sido migrada satisfactoriamente

# Configuración del Módulo de Autenticación LDAP.
authentication:
    default_realm: ldap
    realms:
        ldap:
            credential:
                class: Password
                password_field: password
                password_type:  self_check
            store:
                class: LDAP
                ldap_server: [FQDN LDAP SERVER]
                ldap_server_options:
                    timeout: 30
                binddn: [USER LDAP]
                bindpw: [PASSWORD LDAP]
                start_tls: 0
                start_tls_options:
                    verify: none
                user_basedn: ou=people,dc=example,dc=com
                user_filter: (&(objectClass=posixAccount)(uid=%s))
                user_scope: sub
                user_field: uid
                user_search_options:
                    deref: always
                use_roles: 1
                role_basedn: ou=groups,dc=example,dc=com
                role_filter: (&(objectClass=posixGroup)(memberUid=%s))
                role_scope: sub
                role_field: cn
                role_value: uid
                role_search_options:
                    deref: always
        ad:
            store:
                ad_server: [FQDN AD SERVER]
                binddn: [USER AD]
                bindpw: [PASSWORD AD]
                user_basedn: cn=Users,dc=example,dc=com
                contact_basedn: cn=Contacts,dc=example,dc=com
